#!/usr/bin/env sh
# -*- coding: utf-8 -*-
set -e

# :description: Create a pre-commit hook in .git/hooks that runs harness validation.
#     This script is idempotent: running it again overwrites the hook with the latest version.

HOOK_TARGET=".git/hooks/pre-commit"
VALIDATOR="scripts/harness/validate_harness.sh"

# :description: Refuse a symlink path before writing or chmodding a hook.
# :param path: Repository-relative hook path.
reject_symlink_path() {
    path="$1"
    if [ -L "$path" ]; then
        echo "error: refusing symlink hook destination: $path" >&2
        exit 1
    fi
}

if [ ! -d ".git/hooks" ]; then
    echo "error: not inside a git repository" >&2
    exit 1
fi

reject_symlink_path ".git"
reject_symlink_path ".git/hooks"
reject_symlink_path "$HOOK_TARGET"

if [ -e "$HOOK_TARGET" ]; then
    echo "error: refusing to overwrite existing hook: $HOOK_TARGET" >&2
    exit 1
fi

hook_tmp=".git/hooks/.harness-pre-commit-$$"
rm -f "$hook_tmp"

cat > "$hook_tmp" <<'HOOK_EOF'
#!/usr/bin/env sh
# -*- coding: utf-8 -*-
set -e

# :description: Pre-commit hook generated by setup-hooks.sh.
#     Runs harness validation before allowing the commit.
#     Regenerate this file by running: sh scripts/harness/setup-hooks.sh

if [ -f scripts/harness/validate_harness.sh ]; then
    sh scripts/harness/validate_harness.sh
else
    echo "warning: harness validator not found; skipping validation" >&2
fi
HOOK_EOF

chmod +x "$hook_tmp"
reject_symlink_path "$HOOK_TARGET"
if [ -e "$HOOK_TARGET" ]; then
    rm -f "$hook_tmp"
    echo "error: refusing to overwrite existing hook: $HOOK_TARGET" >&2
    exit 1
fi
mv "$hook_tmp" "$HOOK_TARGET"
echo "installed pre-commit hook: $HOOK_TARGET -> $VALIDATOR"
