[versions]
kotlin = "2.4.10"
ktlint = "14.2.0"
ktlint-engine = "1.8.0"
slf4j = "2.0.18"

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint" }

[libraries]
kotlin-bom = { module = "org.jetbrains.kotlin:kotlin-bom", version.ref = "kotlin" }
kotlin-test-junit5 = { module = "org.jetbrains.kotlin:kotlin-test-junit5" }
ktlint-bom = { module = "com.pinterest.ktlint:ktlint-bom", version.ref = "ktlint-engine" }
ktlint-cli-ruleset-core = { module = "com.pinterest.ktlint:ktlint-cli-ruleset-core" }
ktlint-rule-engine = { module = "com.pinterest.ktlint:ktlint-rule-engine" }
ktlint-rule-engine-core = { module = "com.pinterest.ktlint:ktlint-rule-engine-core" }
ktlint-test = { module = "com.pinterest.ktlint:ktlint-test" }
slf4j-bom = { module = "org.slf4j:slf4j-bom", version.ref = "slf4j" }
slf4j-simple = { module = "org.slf4j:slf4j-simple" }
